on:
  schedule:
    # runs every day at 7:00 AM UTC
    - cron:  '0 7 * * *'
  # push:
    # paths:
      # - R/update_roster.R
      #- R/update-injuries.R
  workflow_dispatch:

name: Update-Rosters

jobs:
  update-rosters:
    name: Update-Rosters
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            nflverse/nflreadr
            nflverse/nflverse-data
            nflverse/nflapi
            nflverse/ngsscrapR

      - name: Update rosters
        run: Rscript -e 'source("src/update_roster.R")'

      - name: Commit and push roster data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data
          git commit -m "Automated roster updates `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"
