on:
  schedule:
    # runs every day at 7:00 AM UTC
    - cron:  '0 7 * * *'
  # push:
    # paths:
      # - R/update_roster.R
      #- R/update-injuries.R
  workflow_dispatch:

name: update-injuries

jobs:
  update-injuries:
    name: update-injuries
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: nflverse/nflreadr

      - name: Update injuries
        run: Rscript -e 'source("src/update-injuries.R")'

      - name: Commit and push injury data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add data
          git commit -m "Automated injury report updates `date`" || echo "No changes to commit"
          git push || echo "No changes to commit"
